Added the missing tools.jar dependency to the sample module
Otherwise as expected, you get the following warning while jetty boots
up:

WARN  | Scanner-0 | Local JVM discovery disabled as this JVM cannot
access com.sun.tools.attach.VirtualMachine due to:
java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine